### ISSUE TITLE
Webchat widget does not respond as "AI:"

### ISSUE THREAD

**Issue by MikPoik** [steamship-core/python-client#414]
With 2.17.3 the  webchat doesn't respond as "AI:", it always responds as "You". The response json is in different format and is missing the "who" attribute:

From browser console:
0: Object { who: "bot", message: "Hi! What can I help you with?" }
1 Object { message: "hi", who: "user" }
2: Object { url: null, publicData: false, text: "Well, well, well, look who decided to say hi to Buddy. What do you want?", … }

​

**Comment by douglas-reid** [comment]
@EniasCailliau is this now fixed, or has it been resolved?

**Comment by MikPoik** [comment]
It seems to be fixed already
