### ISSUE TITLE
bug: the response objects cannot be converted to json

### ISSUE THREAD

**Issue by wunglee** [steamship-core/python-client#439]
#### Create or reuse an instance of the package
instance = Steamship.use("my-package", "instance-id")

#### Invoke the methods
hello_resp = instance.invoke("say_hello", verb="GET", name="Ted")
do_resp = instance.invoke("do_something", number=5)

#### bug  is in version 2.17.11

**Comment by dkolas** [comment]
Thanks again.  These docs were also out of date.  PR is in for fixing them.
