### ISSUE TITLE
bug：chinese encoding error

### ISSUE THREAD

**Issue by wunglee** [steamship-core/python-client#440]
from steamship import Steamship

instance = Steamship.use("PACKAGE_HANDLE", "INSTANCE_HANDLE", config={
    "default_name": "王某"  
})

print(instance.invoke("greet")      #######.  chinese encoding error

**Comment by dkolas** [comment]
Thank you for reporting!  I've been able to reproduce locally.  Will work on a fix.

**Comment by dkolas** [comment]
Hi again - just reporting that I have a backend fix in the works.  Will close this issue once it's deployed to production.
