### ISSUE TITLE
AttributeError: type object 'Block' has no attribute 'CreateRequest'

### ISSUE THREAD

**Issue by wunglee** [steamship-core/python-client#444]
in url:https://docs.steamship.com/packages/cookbook/collecting-and-querying-sentiment.html
    def add_document(self, content: str = None) -> str:
        file = File.create(self.client,
                           blocks=[Block.CreateRequest(text=content)]). # bug here!

bug is in version 2.17.11

**Comment by dkolas** [comment]
Hi there,

My apologies, the docs were out of date.

If you remove the `.CreateRequest`, this should work.

`blocks=[Block(text=content)]`
