### ISSUE TITLE
TypeError: ConfigurableFavoritesPackage.config_cls() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by wunglee** [steamship-core/python-client#450]
##### bug in: 
https://docs.steamship.com/packages/cookbook/adding-configuration.html
https://docs.steamship.com/packages/cookbook/article-tagging.html

TypeError: ConfigurableFavoritesPackage.config_cls() missing 1 required positional argument: 'self'
##### The bug is here:
     def config_cls(self) -> Type[Config]:
          """Return our config object"""
          return self.FavoritesConfig

##### must be change to:
    @classmethod
    def config_cls(cls) -> Type[Config]:
          """Return our config object"""
        return cls.FavoritesConfig

**Comment by douglas-reid** [comment]
@wunglee thanks for the report! we now have a pending PR for this cleanup
