### ISSUE TITLE
How to delete a version that has been deployed but no instance created?

### ISSUE THREAD

**Issue by wunglee** [steamship-core/python-client#451]
How to delete a version that has been deployed but no instance created?

**Comment by dkolas** [comment]
This is WIP in both the web app and the SDK. #442 will allow in SDK.

**Comment by dkolas** [comment]
This is now possible in the SDK.  See PluginVersion.delete() and PackageVersion.delete().

I'm going to leave this issue open until we have a button in the web portal as well.

**Comment by dkolas** [comment]
PluginVersions and PackageVersions can now be deleted from the web portal as well.
