### ISSUE TITLE
Support Vertex AI PaLM

### ISSUE THREAD

**Issue by Goktug** [steamship-core/python-client#547]
Hey Steamship team,

I noticed that you currently only support OpenAI in your Agent LLM stack. I am curious if I can use "ChatVertexAI" without any issues since it is already supported by the LangChain. 

https://python.langchain.com/docs/integrations/chat/google_vertex_ai_palm

If yes, as a follow-up question: Are there any limitations I should be aware of if I don't use one of your library's supported LLM options?

**Comment by GitOnUp** [comment]
Hi @Goktug, the short answer is: not easily, but technically possible with non-trivial work, and this dives into heavily advanced usage that may change interfaces soon.  This should be easier, later.

In any case I've noted the desire for Vertex AI PaLM support in our internal tracking systems.

**Comment by ishaan-jaff** [comment]
Hi @Goktug @GitOnUp  I believe we can help with this issue. I’m the maintainer of LiteLLM https://github.com/BerriAI/litellm

**TLDR:**
**We allow you to use any LLM as a drop in replacement for `gpt-3.5-turbo`. 
If you don't have access to the LLM you can use the LiteLLM proxy to make requests to the LLM**

You can use LiteLLM in the following ways:

## With your own API KEY:
This calls the provider API directly

```python
from litellm import completion
import os
## set ENV variables 
os.environ["OPENAI_API_KEY"] = "your-key" # 
os.environ["COHERE_API_KEY"] = "your-key" # 

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion(model="command-nightly", messages=messages)
```

## Using the LiteLLM Proxy with a LiteLLM Key 
this is great if you don’t have access to claude but want to use the open source LiteLLM proxy to access claude


```python
from litellm import completion
import os

## set ENV variables 
os.environ["OPENAI_API_KEY"] = "sk-litellm-5b46387675a944d2" # [OPTIONAL] replace with your openai key
os.environ["COHERE_API_KEY"] = "sk-litellm-5b46387675a944d2" # [OPTIONAL] replace with your cohere key

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion(model="command-nightly", messages=messages)
```
