### ISSUE TITLE
Request for Server-Side Support for gpt-4o and gpt-4-turbo in Steamship API

### ISSUE THREAD

**Issue by bestmgmt** [steamship-core/python-client#602]
Hello Steamship Team,

I am a subscriber of Steamship.com and have been utilizing your services extensively.

With the recent release of gpt-4o and gpt-4-turbo ([OpenAI Models](https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4)), I wanted to inquire if you could add server-side support for these two new modles in your API. When attempting to use them with the current API, I encountered the following error:

`an error occurred: The instance you are attempting to invoke failed initialization and cannot be used.  Init failure message: Initialization Failed Wrapped Message: This plugin cannot be used with model gpt-4o while using Steamship's API key. Valid models are ['gpt-4', 'gpt-4-0314', 'gpt-4-0613', 'gpt-4-32k', 'gpt-4-32k-0613', 'gpt-3.5-turbo', 'gpt-3.5-turbo-0613', 'gpt-3.5-turbo-16k', 'gpt-3.5-turbo-16k-0613', 'gpt-4-1106-preview']`

Adding support for gpt-4o and gpt-4-turbo would be greatly beneficial for users, allowing us to leverage the latest advancements in the GPT through your platform.

Thank you for your attention to this matter.

**Comment by bestmgmt** [comment]
any updates? @eob @gregwhelan @dkolas @GitOnUp

**Comment by bestmgmt** [comment]
any updates please? @eob @gregwhelan @dkolas @GitOnUp

**Comment by bestmgmt** [comment]
Hi dear support,

I am still waiting on this as a paying client.

Thanks for your consideration,

@eob @gregwhelan @dkolas @GitOnUp

**Comment by eob** [comment]
Hi @bestmgmt -- with apologies, we have no plans to add gpt-4o at this time. We may add `gpt-4-turbo` at a future date, and will let you know if we do!
